server:
  port: 8080
  tomcat:
    connectionTimeout: 300

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ably?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: ably1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_size: 100
        order_inserts: true
        order_updates: true
        format_sql: true
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger
    doc-expansion: none